import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <div>HomeLayout:</div>

        <nav style={{ backgroundColor: "#555", padding: "5px" }}>
          <span>home Navbar: </span>
          <a href="/">Home</a>
          <span> | </span>
          <a href="/about">About</a>
          <span> | </span>
          <a href="/blog">Blog</a>
          <span> | </span>
          <a href="/blog/first-blog">Blog Post</a>
        </nav>

        <div className="debug">{children}</div>
      </body>
    </html>
  );
}
